path_classifiers:
  test:
    - test
  library:
    - extern/qfr

extraction:
  cpp:
    prepare:
      packages:
        - python-pip
    after_prepare:
      - export PATH=~/.local/bin:$PATH
      - pip3 install cmake --user
      - pip3 install z3-solver --user
      - cmake --version
    configure:
      command:
        - export Z3_ROOT=~/.local/lib/python3.8/site-packages/z3
        - export Z3_DIR=~/.local/lib/python3.8/site-packages/z3
        - cmake -S . -B build -DBUILD_QMAP_TESTS=ON -DBUILD_QFR_TESTS=ON -DBUILD_DD_PACKAGE_TESTS=ON -DBINDINGS=ON
    index:
      build_command:
        - cmake --build build --parallel 2
  python:
    python_setup:
      version: 3
