version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  jobs:
    post_create_environment:
      - pip install "z3-solver>=4.8.15"
      - Z3_ROOT=$(python -c "import z3 as _; print(_.__path__[0])"); export Z3_ROOT; pip install -e .[docs] -v

sphinx:
  configuration: docs/source/conf.py
