version: 2

formats:
  - pdf
  - htmlzip

build:
  os: ubuntu-24.04
  tools:
    python: "3.12"
  apt_packages:
    - graphviz
    - inkscape
  jobs:
    post_checkout:
      # Skip docs build if the commit message contains "skip ci"
      - (git --no-pager log --pretty="tformat:%s -- %b" -1 | grep -viq "skip ci") || exit 183
      # Skip docs build if there are no changes related to docs
      - |
        if [ "$READTHEDOCS_VERSION_TYPE" = "external" ] && git diff --quiet origin/main -- docs/ .readthedocs.yaml src/mqt/ src/python include/*/python .github/contributing* .github/support*;
        then
          exit 183;
        fi
      # Unshallow the git clone and fetch tags to get proper version information
      - git fetch --unshallow --tags
    pre_build:
      # Set up uv
      - asdf plugin add uv
      - asdf install uv latest
      - asdf global uv latest
      - wget https://github.com/Z3Prover/z3/releases/download/z3-4.13.4/z3-4.13.4-x64-glibc-2.35.zip
      - unzip z3-4.13.4-x64-glibc-2.35.zip -d ~/
      # Set up build time dependencies including a source distribution of mqt-core.
      - uv sync --only-group build --only-group docs --no-binary-package mqt-core
      # The default version of CMake on Ubuntu 24.04 is too old, so we need to install a newer version.
      - uv pip install cmake
    build:
      html:
        - Z3_ROOT=~/z3-4.13.4-x64-glibc-2.35 uv run --frozen --no-dev --no-build-isolation-package mqt-qmap -m sphinx -T -b html -d docs/_build/doctrees -D language=en docs $READTHEDOCS_OUTPUT/html
      htmlzip:
        - Z3_ROOT=~/z3-4.13.4-x64-glibc-2.35 uv run --frozen --no-dev --no-build-isolation-package mqt-qmap -m sphinx -T -b dirhtml -d docs/_build/doctrees -D language=en docs docs/_build/dirhtml
        - mkdir -p $READTHEDOCS_OUTPUT/htmlzip
        - zip -r $READTHEDOCS_OUTPUT/htmlzip/html.zip docs/_build/dirhtml/*
      pdf:
        - Z3_ROOT=~/z3-4.13.4-x64-glibc-2.35 uv run --frozen --no-dev --no-build-isolation-package mqt-qmap -m sphinx -T -b latex -d docs/_build/doctrees -D language=en docs docs/_build/latex
        - cd docs/_build/latex && latexmk -pdf -f -dvi- -ps- -interaction=nonstopmode -jobname=$READTHEDOCS_PROJECT
        - mkdir -p $READTHEDOCS_OUTPUT/pdf
        - cp docs/_build/latex/$READTHEDOCS_PROJECT.pdf $READTHEDOCS_OUTPUT/pdf/$READTHEDOCS_PROJECT.pdf

sphinx:
  configuration: docs/conf.py
