version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  apt_packages:
    - cmake
  jobs:
    pre_install:
      - pip install z3-solver>=4.8.15
      - export Z3_ROOT=$(python -c "import z3, os; print(os.path.dirname(z3.__file__))")

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
