version: 2

submodules:
  include: all
  recursive: true

build:
  os: ubuntu-22.04
  tools:
    python: "3.9"
  jobs:
    pre_create_environment:
      - pip install "z3-solver>=4.8.15"
      - python -c "import z3 as _; print(_.__path__)"

sphinx:
  configuration: docs/source/conf.py

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
